# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _ising
else:
    import _ising

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ising.delete_SwigPyIterator

    def value(self):
        return _ising.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ising.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ising.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ising.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ising.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ising.SwigPyIterator_copy(self)

    def next(self):
        return _ising.SwigPyIterator_next(self)

    def __next__(self):
        return _ising.SwigPyIterator___next__(self)

    def previous(self):
        return _ising.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ising.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ising.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ising.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ising.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ising.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ising.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ising.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ising:
_ising.SwigPyIterator_swigregister(SwigPyIterator)
class vector_double(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _ising.vector_double_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ising.vector_double___nonzero__(self)

    def __bool__(self):
        return _ising.vector_double___bool__(self)

    def __len__(self):
        return _ising.vector_double___len__(self)

    def __getslice__(self, i, j):
        return _ising.vector_double___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ising.vector_double___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ising.vector_double___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ising.vector_double___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ising.vector_double___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ising.vector_double___setitem__(self, *args)

    def pop(self):
        return _ising.vector_double_pop(self)

    def append(self, x):
        return _ising.vector_double_append(self, x)

    def empty(self):
        return _ising.vector_double_empty(self)

    def size(self):
        return _ising.vector_double_size(self)

    def swap(self, v):
        return _ising.vector_double_swap(self, v)

    def begin(self):
        return _ising.vector_double_begin(self)

    def end(self):
        return _ising.vector_double_end(self)

    def rbegin(self):
        return _ising.vector_double_rbegin(self)

    def rend(self):
        return _ising.vector_double_rend(self)

    def clear(self):
        return _ising.vector_double_clear(self)

    def get_allocator(self):
        return _ising.vector_double_get_allocator(self)

    def pop_back(self):
        return _ising.vector_double_pop_back(self)

    def erase(self, *args):
        return _ising.vector_double_erase(self, *args)

    def __init__(self, *args):
        _ising.vector_double_swiginit(self, _ising.new_vector_double(*args))

    def push_back(self, x):
        return _ising.vector_double_push_back(self, x)

    def front(self):
        return _ising.vector_double_front(self)

    def back(self):
        return _ising.vector_double_back(self)

    def assign(self, n, x):
        return _ising.vector_double_assign(self, n, x)

    def resize(self, *args):
        return _ising.vector_double_resize(self, *args)

    def insert(self, *args):
        return _ising.vector_double_insert(self, *args)

    def reserve(self, n):
        return _ising.vector_double_reserve(self, n)

    def capacity(self):
        return _ising.vector_double_capacity(self)
    __swig_destroy__ = _ising.delete_vector_double

# Register vector_double in _ising:
_ising.vector_double_swigregister(vector_double)
class Ising(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, iJ=1.0, iL=10, iN_flips_per_step=100, iT=2.0, iH=0.0):
        _ising.Ising_swiginit(self, _ising.new_Ising(iJ, iL, iN_flips_per_step, iT, iH))

    def resetAverages(self):
        return _ising.Ising_resetAverages(self)

    def computeBoltzmannFactors(self):
        return _ising.Ising_computeBoltzmannFactors(self)

    def thermalize(self, n_therm):
        return _ising.Ising_thermalize(self, n_therm)

    def metropolisStep(self):
        return _ising.Ising_metropolisStep(self)

    def oneMCStepPerSpin(self):
        return _ising.Ising_oneMCStepPerSpin(self)

    def magnetizationPerSpin(self):
        return _ising.Ising_magnetizationPerSpin(self)

    def energyPerSpin(self):
        return _ising.Ising_energyPerSpin(self)

    def run(self, n_mc_steps):
        return _ising.Ising_run(self, n_mc_steps)

    def get_mAvg(self):
        return _ising.Ising_get_mAvg(self)

    def get_m2Avg(self):
        return _ising.Ising_get_m2Avg(self)

    def get_eAvg(self):
        return _ising.Ising_get_eAvg(self)

    def get_e2Avg(self):
        return _ising.Ising_get_e2Avg(self)

    def get_m_vals(self):
        return _ising.Ising_get_m_vals(self)

    def get_E_vals(self):
        return _ising.Ising_get_E_vals(self)
    __swig_destroy__ = _ising.delete_Ising

# Register Ising in _ising:
_ising.Ising_swigregister(Ising)

